New `llms` command
CoinFabrik/geppetto pull request #67
Opened 2024-08-13 16:21 UTC by NinaTea

- New directory `docs/`. There are brief explanations of `llm_api_handler.md` and `slack_handler.md`
- In `slack_handler.md` there is a note on how to add new commands
- New variable `self.commands` in `geppetto/slack_handler.py` which only contains `llms`
- New functions `handle_command()` and `list_llms()` in `geppetto/slack_handler.py`
- Modification of `handle_message`, when it receives a message, it checks whether it is actually a message or a command; if it is a command, `handle_command()` is called.
- Update of README
- 2 new tests in `tests/test_slack.py`, `test_command_not_written_properly()` and `test_handle_command()`.

2024-08-13 21:19 UTC, tenuki requested changes
Mas allá de los cambios acá mencionados, aplicaría linting a todos los fuentes.. y trataría de que esté mucho mas cerca de PEP8.. no pido 100% compliance.. pero estar mas cerca estaría buenisimo..

2024-08-13 21:19 UTC, tenuki commented on geppetto/slack_handler.py
>      def handle_message(self, msg, channel_id, thread_id):
esta función habría que partirla en sus diferentes partes..

2024-08-13 21:19 UTC, tenuki commented on geppetto/slack_handler.py
> +        if isinstance(formated_msg, str):
esto debería ocurrir en el caso del ! response["ok"] ?

2024-08-13 21:19 UTC, tenuki commented on docs/llm_api_handler.md
> +## LLM Handler
no sé si pondria estos comentarios acá.. o en el código con docstrings... me parece que eso seria mas adecuado.. con esta y con la doc de slack_handler...

2024-08-15 13:37 UTC, NinaTea commented on tests/test_slack.py
> +        MOCK_LIST_LLMS_RESPONSE = "Here are the available AI models!\n"
Totalmente cierto! Arreglado

2024-08-15 13:45 UTC, NinaTea commented on tests/test_slack.py
> +        MOCK_LIST_LLMS_RESPONSE = MOCK_LIST_LLMS_RESPONSE + reminder
Cambiado junto con el uso de `+=` ! :)

2024-08-15 13:45 UTC, NinaTea commented on tests/test_slack.py
> +        thread_id = "test_thread_id"
Sip, quedaron globales

2024-08-15 13:46 UTC, NinaTea commented on geppetto/slack_handler.py
> +        self.commands = ['llms']
Elegí el diccionario con el método asociado :)

2024-08-15 13:46 UTC, NinaTea commented on geppetto/slack_handler.py
>      def handle_message(self, msg, channel_id, thread_id):
La partí en dos funciones `use_prompt_from_thread()` y `post_response()`

2024-08-15 13:46 UTC, NinaTea commented on geppetto/slack_handler.py
> +        if isinstance(formated_msg, str):
cambié el manejo del error

2024-08-15 13:46 UTC, NinaTea commented on docs/llm_api_handler.md
> +## LLM Handler
Borré `docs/` y agregué docstrings

2024-08-20 12:30 UTC, tenuki approved these changes
all ok

2024-08-20 14:21 UTC, merged